app/assets/urls.py
from django.urls import path

from .views import (
    ComputerCreateView,
    ComputerDetailView,
    ComputerListView,
    ComputerModelCreateView,
    ComputerModelDetailView,
    ComputerModelListView,
    ComputerModelUpdateView,
    ComputerUpdateView,
    MicrosoftOfficeDetailView,
    MicrosoftOfficeListView,
    MicrosoftOfficeUpdateView,
    MonitorCreateView,
    MonitorDetailView,
    MonitorListView,
    MonitorModelCreateView,
    MonitorModelDetailView,
    MonitorModelListView,
    MonitorModelUpdateView,
    MonitorUpdateView,
    PrinterCreateView,
    PrinterDetailView,
    PrinterListView,
    PrinterModelCreateView,
    PrinterModelDetailView,
    PrinterModelListView,
    PrinterModelUpdateView,
    PrinterUpdateView,
    add_computer_comment_view,
    computer_filter_view,
    printer_filter_view,
    # get_next_computer_name_view,
)

urlpatterns = [
    # path("get_next_computer_name/", get_next_computer_name_view, name="get-next-computer-name"),
    path("computer_filter/", computer_filter_view, name="computer-filter"),
    path("computer_printer/", printer_filter_view, name="printer-list"),
    path("computers/", ComputerListView.as_view(), name="computer-list"),
    path(
        "computer-models/", ComputerModelListView.as_view(), name="computer-model-list"
    ),
    path(
        "computer/detail/<int:pk>/",
        ComputerDetailView.as_view(),
        name="computer-detail",
    ),
    path(
        "computer/update/<int:pk>/",
        ComputerUpdateView.as_view(),
        name="computer-update",
    ),
    path(
        "computer/add-comment/<int:pk>/",
        add_computer_comment_view,
        name="add-computer-comment",
    ),
    path("add/computer/", ComputerCreateView.as_view(), name="computer-create"),
    path(
        "computer-model/detail/<int:pk>/",
        ComputerModelDetailView.as_view(),
        name="computer-model-detail",
    ),
    path(
        "computer-model/update/<int:pk>/",
        ComputerModelUpdateView.as_view(),
        name="computer-model-update",
    ),
    path(
        "add/computer-model/",
        ComputerModelCreateView.as_view(),
        name="computer-model-create",
    ),
    path("printers/", PrinterListView.as_view(), name="printer-list"),
    path("printer-models/", PrinterModelListView.as_view(), name="printer-model-list"),
    path(
        "printer/detail/<int:pk>/",
        PrinterDetailView.as_view(),
        name="printer-detail",
    ),
    path(
        "printer/update/<int:pk>/",
        PrinterUpdateView.as_view(),
        name="printer-update",
    ),
    path("add/printer/", PrinterCreateView.as_view(), name="printer-create"),
    path(
        "printer-model/detail/<int:pk>/",
        PrinterModelDetailView.as_view(),
        name="printer-model-detail",
    ),
    path(
        "printer-model/update/<int:pk>/",
        PrinterModelUpdateView.as_view(),
        name="printer-model-update",
    ),
    path(
        "add/printer-model/",
        PrinterModelCreateView.as_view(),
        name="printer-model-create",
    ),
    path("monitor/", MonitorListView.as_view(), name="monitor-list"),
    path("monitor-models/", MonitorModelListView.as_view(), name="monitor-model-list"),
    path(
        "monitor/detail/<int:pk>/",
        MonitorDetailView.as_view(),
        name="monitor-detail",
    ),
    path(
        "monitor/update/<int:pk>/",
        MonitorUpdateView.as_view(),
        name="monitor-update",
    ),
    path("add/monitor/", MonitorCreateView.as_view(), name="monitor-create"),
    path(
        "monitor-model/detail/<int:pk>/",
        MonitorModelDetailView.as_view(),
        name="monitor-model-detail",
    ),
    path(
        "monitor-model/update/<int:pk>/",
        MonitorModelUpdateView.as_view(),
        name="monitor-model-update",
    ),
    path(
        "add/monitor-model/",
        MonitorModelCreateView.as_view(),
        name="monitor-model-create",
    ),
    path(
        "microsoft-office/",
        MicrosoftOfficeListView.as_view(),
        name="microsoft-office-list",
    ),
    path(
        "microsoft-office/detail/<int:pk>/",
        MicrosoftOfficeDetailView.as_view(),
        name="microsoft-office-detail",
    ),
    path(
        "microsoft-office/update/<int:pk>/",
        MicrosoftOfficeUpdateView.as_view(),
        name="microsoft-office-update",
    ),
]

app/cf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("assets/", include("assets.urls")),
    path("customers", include("customers.urls")),
    path("", include("tickets.urls")),
    path("", include("pwa.urls")),
    # path("accounts/", include("allauth.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/assets/models.py
from customers.models import Customer, Department
from django.db import models
from django.shortcuts import reverse


# class ComputerName(models.Model):
#     computer_name = models.CharField(max_length=100, unique=True)
#     last_used_number = models.IntegerField(default=0)

#     def save(self, *args, **kwargs):
#         if not self.pk:  # Checking if the instance is not yet saved
#             computer_name_prefix = 'MCWT'
#             last_computer_name = ComputerName.objects.order_by("-last_used_number").first()
#             if last_computer_name:
#                 self.last_used_number = last_computer_name.last_used_number + 1
#             else:
#                 self.last_used_number = 1  # Start from 1 if no records exist
#             self.computer_name = f"{computer_name_prefix}{self.last_used_number}"
#         super().save(*args, **kwargs)

#     def __str__(self):
#         return self.computer_name


class Project(models.Model):
    name = models.CharField(max_length=100)
    details = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class Location(models.Model):
    name = models.CharField(max_length=100)
    details = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name.upper()


class Maker(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name.upper()


class Status(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "Statuses"
        ordering = ["name"]

    def __str__(self):
        return self.name.upper()


class OperatingSystem(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class MonitorModel(models.Model):
    name = models.CharField(max_length=100)
    maker = models.ForeignKey(Maker, on_delete=models.CASCADE)
    image = models.FileField(upload_to="monitor_models/", blank=True, null=True)

    class Meta:
        ordering = ["name"]

    def get_absolute_url(self):
        return reverse("monitor-model-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return f"{self.maker} - {self.name}"


class Monitor(models.Model):
    serial_number = models.CharField(max_length=100, blank=True, null=True)
    model = models.ForeignKey(
        MonitorModel, on_delete=models.CASCADE, related_name="monitors"
    )
    date_received = models.DateField(blank=True, null=True)
    date_installed = models.DateField(blank=True, null=True)
    notes = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ["model__name"]

    def get_absolute_url(self):
        return reverse("monitor-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return f"{self.model.name} - {self.serial_number}"


class ComputerType(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name.upper()


class ComputerModel(models.Model):
    name = models.CharField(max_length=100)
    computer_type = models.ForeignKey(ComputerType, on_delete=models.CASCADE)
    maker = models.ForeignKey(Maker, on_delete=models.CASCADE)
    processor = models.CharField(
        max_length=100, blank=True, null=True, help_text="In GHz(e.g.:i5 2.9 GHz)"
    )
    ram = models.IntegerField("RAM", help_text="In GB")
    hdd = models.IntegerField("HDD/Storage", help_text="In GB")

    class Meta:
        ordering = ["name"]

    def get_absolute_url(self):
        return reverse("computer-model-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return f"{self.maker} - {self.name} - {self.processor}"


class Computer(models.Model):
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE,
        related_name="projects",
        null=True,
        blank=True,
    )
    serial_number = models.CharField(max_length=100, blank=True, null=True)
    warranty_info = models.CharField("Warranty", max_length=100)
    computer_name = models.CharField(max_length=100, blank=True, null=True)
    model = models.ForeignKey(
        ComputerModel, on_delete=models.CASCADE, related_name="computers"
    )
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    monitor = models.ManyToManyField(Monitor, related_name="monitors", blank=True)
    os = models.ForeignKey(
        OperatingSystem,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="Operating System",
    )
    location = models.ForeignKey(
        Location,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name="computer_locations",
    )
    department = models.ForeignKey(
        Department,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name="computer_departments",
    )
    user = models.CharField(max_length=100, blank=True, null=True)
    date_received = models.DateField(blank=True, null=True)
    date_installed = models.DateField(blank=True, null=True)
    image = models.FileField(upload_to="system_audit/", blank=True, null=True)
    notes = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ["computer_name"]

    def get_absolute_url(self):
        return reverse("computer-detail", kwargs={"pk": self.pk})

    def __str__(self):
        if self.serial_number:
            return self.serial_number
        return self.computer_name


class ComputerComment(models.Model):
    computer = models.ForeignKey(
        Computer, on_delete=models.CASCADE, related_name="comments"
    )
    comment = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.computer.computer_name} - comment {self.pk}"


class PrinterModel(models.Model):
    name = models.CharField(max_length=100)
    maker = models.ForeignKey(Maker, on_delete=models.CASCADE)
    image = models.FileField(upload_to="printer_models/", blank=True, null=True)

    class Meta:
        ordering = ["name"]

    def get_absolute_url(self):
        return reverse("printer-model-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return f"{self.maker} - {self.name}"


class Printer(models.Model):
    serial_number = models.CharField(max_length=100, blank=True, null=True)
    printer_name = models.CharField(max_length=100, blank=True, null=True)
    model = models.ForeignKey(
        PrinterModel, on_delete=models.CASCADE, related_name="printers"
    )
    ip_addr = models.GenericIPAddressField("IP Address", blank=True, null=True)
    location = models.ForeignKey(
        Location,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name="printer_locations",
    )
    department = models.ForeignKey(
        Department,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name="printer_departments",
    )
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    date_received = models.DateField(blank=True, null=True)
    date_installed = models.DateField(blank=True, null=True)
    notes = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ["ip_addr"]

    def get_absolute_url(self):
        return reverse("printer-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return f"{self.model.maker} - {self.model.name}"


class MicrosoftOfficeVersion(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return f"Microsoft Office {self.name}"


class MicrosoftOffice(models.Model):
    version = models.ForeignKey(
        MicrosoftOfficeVersion, on_delete=models.CASCADE, related_name="versions"
    )
    product_key = models.CharField(max_length=30, unique=True)
    computer = models.ForeignKey(
        Computer,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        help_text="serial number",
        related_name="office_installations",
    )
    date_installed = models.DateField(blank=True, null=True)
    comments = models.TextField(blank=True, null=True)
    is_installed = models.BooleanField(default=False)
    has_failed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-date_installed"]

    def get_absolute_url(self):
        return reverse("microsoft-office-detail", kwargs={"pk": self.pk})

    def remove_hyphens(self):
        return self.product_key.replace("-", "")

    def __str__(self):
        return f"{self.version} - XXXXX-XXXXX-XXXXX-{self.product_key[-11:]}"

app/assets/forms.py
from django import forms

from .models import (
    Computer,
    ComputerComment,
    # ComputerName,
    MicrosoftOffice,
    Monitor,
    Printer,
)


# class GetComputerNameForm(forms.ModelForm):

#     class Meta:
#         model = ComputerName
#         fields = ["computer_name"]


class MicrosoftOfficeUpdateForm(forms.ModelForm):
    class Meta:
        model = MicrosoftOffice
        fields = ["computer", "date_installed", "has_failed", "comments"]
        widgets = {
            "date_installed": forms.DateInput(attrs={"type": "date"}),
            "comments": forms.Textarea(attrs={"rows": 2}),
        }


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = ComputerComment
        fields = ["comment"]
        widgets = {
            "comment": forms.Textarea(
                attrs={
                    "rows": 2,
                }
            )
        }


class PrinterForm(forms.ModelForm):
    class Meta:
        model = Printer
        fields = "__all__"
        widgets = {
            "date_received": forms.DateInput(attrs={"type": "date"}),
            "date_installed": forms.DateInput(attrs={"type": "date"}),
        }


class MonitorForm(forms.ModelForm):
    class Meta:
        model = Monitor
        fields = "__all__"
        widgets = {
            "date_received": forms.DateInput(attrs={"type": "date"}),
            "date_installed": forms.DateInput(attrs={"type": "date"}),
        }


class ComputerForm(forms.ModelForm):
    class Meta:
        model = Computer
        fields = "__all__"
        # exclude = ["project_name"]
        widgets = {
            "date_received": forms.DateInput(attrs={"type": "date"}),
            "date_installed": forms.DateInput(attrs={"type": "date"}),
        }

app/templates/assets/computer_filter.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="p-5 mb-5">
    <h1>Computer Filter</h1>
    <hr>
    <div class="col-lg-4">
        <form method="get">
            {{ filter.form|crispy }}
            <div class="d-grid">
                <input class="btn btn-dark rounded-4"
                    type="submit" />
            </div>
        </form>
    </div>
    <br>
    <section>
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a
                    href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of
                    {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last
                    &raquo;</a>
                {% endif %}
            </span>
        </div>

        <div class="table-responsive px-5">
            <table class="table table-hover table-sm small">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Computer name</th>
                        <th scope="col">Serial number</th>
                        <th scope="col">Model</th>
                        <th scope="col">Location</th>
                        <th scope="col">Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for computer in filter.qs %}
                    <tr>
                        <th scope="row">{{forloop.counter}}</th>
                        <td><a class="text-dark"
                                href="{% url 'computer-detail' computer.pk %}">{{computer.computer_name|upper}}
                            </a>
                        </td>
                        <td>{{computer.serial_number|upper}}</td>
                        <td>{{computer.model|upper}}</td>
                        <td>{{computer.location|upper}}</td>
                        <td>{{computer.status|upper}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a
                    href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of
                    {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last
                    &raquo;</a>
                {% endif %}
            </span>
        </div>
    </section>
</div>

{% endblock content %}

app/templates/assets/computermodel_detail.html
{% extends 'base.html' %}


{% block content %}
<div class="container py-5 mb-5">
    <h1>{{object}}</h1>
    <hr>
    <div class="text-end">
        <a class="btn btn-dark"
            href="{% url 'computer-model-update' object.pk %}">Edit</a>
    </div>
    <div class="col-lg-4">
        <p>Computer Type: {{object.computer_type}}</p>
        <p>Maker: {{object.maker}}</p>
        <p>Processor: {{object.processor}}</p>
        <p>RAM: {{object.ram}} GB</p>
        <p>Storage: {{object.hdd}} GB</p>

        <hr>
        <p>Computers</p>
        <ol>
            {% for computer in object.computers.all %}
            <li><a href="{{computer.get_absolute_url}}">{{computer}}</a></li>
            {% endfor %}
        </ol>
    </div>
</div>
{% endblock content %}

app/templates/assets/computers.html
{% extends 'base.html' %}


{% block content %}

<div class="p-5 mb-5">
    <section>
        <h1>Computer models</h1>
        <hr>
        <div class="text-end">
            <a href="{% url 'computer-model-create' %}">
                <span class="text-success material-symbols-outlined">
                    add_box
                </span>
            </a>
        </div>
        <div class="table-responsive px-5">
            <table class="table table-sm small">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Model</th>
                        <th scope="col">Processor</th>
                        <th scope="col">RAM (GB)</th>
                        <th scope="col">Storage (GB)</th>
                    </tr>
                </thead>
                <tbody>
                    {% for model in computer_models %}
                    <tr>
                        <th scope="row">{{forloop.counter}}</th>
                        <td><a class="text-dark"
                                href="{% url 'computer-model-detail' model.pk %}">{{model}}</a>
                        </td>
                        <td>{{model.processor}}</td>
                        <td>{{model.ram}}</td>
                        <td>{{model.hdd}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </section>
  
</div>

{% endblock content %}

app/templates/assets/get_computer_name.html
{% extends 'base.html' %}


{% block content %}
    <div class="container">
        {{last_computer_name}}
    </div>
{% endblock content %}
    

app/templates/assets/microsoftoffice_detail.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}


{% block content %}
<div class="container py-5 mb-5">
    <h5>{{object}}</h5>
    <hr>
    <div class="col-lg-5 p-5 rounded-4 border shadow">
        <p>Product key:
            XXXXX-XXXXX-XXXXX-{{object.product_key|slice:"-11:"|upper}}
            <span class="material-symbols-outlined"
                title="copy product key"
                style="cursor:pointer"
                onclick="copyToClipboard('#getProductKey')">
                content_copy
            </span>
        </p>
        <p>Computer: <a href="{{object.computer.get_absolute_url}}">
                {{object.computer|default:'Not installed'}}</a></p>
        <p>Installed: {{object.date_installed|default:'Not installed'}}</p>
        <p>Comments: {{object.comments}}</p>
        <span hidden
            id="getProductKey"
            value="{{object.remove_hyphens}}">
            {{object.remove_hyphens}}</span>
        {% if not object.is_installed %}
        <hr>

        <form action="{% url 'microsoft-office-update' object.pk %}"
            method="post">
            {% csrf_token %}
            {{microsoft_office_update_form|crispy}}
            <button class="btn btn-dark"
                type="submit">Submit</button>
        </form>
        {% endif %}

    </div>
</div>
<ul hidden
    id="keyCopiedMessage">
    <div style="position: fixed; left:2%; bottom:7%; width:fit-content; z-index:1000;"
        class="hide-me alert rounded-4 border-info  alert-info alert-dismissible fade show"
        role="alert">
        <strong class="d-flex flex-wrap">Copied</strong>
        <button type="button"
            class="btn-close"
            data-bs-dismiss="alert"
            aria-label="Close"></button>
    </div>
</ul>
<script>
    function copyToClipboard(element) {
        var $temp = $("<input>");
        $("body").append($temp);
        $temp.val($(element).text().trim()).select();
        document.execCommand("copy");
        $temp.remove();
        document.getElementById("keyCopiedMessage").toggleAttribute("hidden");
    }
    $("#id_computer").select2();
</script>
{% endblock content %}

app/templates/assets/microsoftoffice_list.html
{% extends 'base.html' %}


{% block content %}
<div class="p-5 mb-5">
    <h5>Microsoft Office
        ({{microsoft_office_installed_count}}/{{microsoft_office_count}})</h5>
    <hr>
    <div class="col-lg-6 mx-auto py-3">
        <form action=""
            method="get">
            <input class="form-control form-control-lg rounded-4"
                type="search"
                name="microsoft_office_search"
                placeholder="Search Microsoft Office keys..."
                id="">
        </form>
    </div>
    <br>
    <section>
        <div class="table-responsive px-5">
            <table class="table table-hover table-sm small">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Product Key</th>
                        <th scope="col">Computer</th>
                        <th scope="col">Installed</th>
                    </tr>
                </thead>
                <tbody>
                    {% for key in object_list %}
                    <tr>
                        <th scope="row">{{forloop.counter}}</th>
                        <td><a class="text-dark"
                                href="{% url 'microsoft-office-detail' key.pk %}">{{key}}
                            </a>
                        </td>
                        <td>{{key.computer|default:'Available'}}</td>
                        <td>{{key.date_installed|default:'Available'}}</td>
                    </tr>
                    {% empty %}
                    <td colspan="4">
                        <p class="text-center">No available keys</p>
                    </td>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </section>
</div>


{% endblock content %}

app/templates/assets/monitor_detail.html
{% extends 'base.html' %}


{% block content %}
<div class="container py-5 mb-5">
    <h1>{{object}}</h1>
    <hr>
    <div class="text-end py-3">
        <a class="btn btn-dark"
            href="{% url 'monitor-update' object.pk %}">Edit</a>
    </div>
    <div class="row">
        <div class="col-md-4">
            <p>Serial Number: {{object.serial_number}}</p>
            <p>Computer: <a
                    href="{{object.monitors.last.get_absolute_url}}">{{object.monitors.last}}</a>
            </p>
            <p>Model: <a
                    href="{{object.model.get_absolute_url}}">{{object.model}}</a>
            </p>
        </div>
        <div class="col-md-4">
            <p>Received: {{object.date_received}}</p>
            <p>Installed: {{object.date_installed}}</p>
            <p>Notes: {{object.notes}}</p>
        </div>

    </div>
</div>
{% endblock content %}

app/templates/assets/monitor_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container py-5 mb-5">
    <h1>Add Monitor</h1>
    <hr>
    <div class="col-lg-5 p-5 rounded-4 border border-dark">
        <form action=""
            enctype="multipart/form-data"
            method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="d-grid">
                <button class="btn btn-dark rounded-4"
                    type="submit">Submit</button>
            </div>
        </form>
    </div>
</div>
<script>
    $("#id_model").select2();
</script>
{% endblock content %}

app/templates/assets/monitor_list.html
{% extends 'base.html' %}


{% block content %}
<div class="p-5 mb-5">
    <div class="d-flex justify-content-start align-items-center">
        <h1>Monitors</h1>
        <div class="ms-3">
            <a href="{% url 'monitor-create' %}">
                <span class="fs-3 text-success material-symbols-outlined">
                    add_box
                </span>
            </a>
        </div>
    </div>
    <hr>

    <div class="col-lg-4 py-3">
        <form action=""
            method="get">
            <input class="form-control form-control-lg rounded-4"
                type="search"
                name="monitors"
                placeholder="Search monitors..."
                id="">
        </form>
    </div>
    <br>
    <section>
        <div class="table-responsive">
            <div class="col-lg-4 p-5 rounded-4 border border-dark">
                <table class="table table-hover table-sm small">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Serial number</th>
                            <th scope="col">Monitor model</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for monitor in object_list %}
                        <tr>
                            <th scope="row">{{forloop.counter}}</th>
                            <td><a class="text-dark"
                                    href="{% url 'monitor-detail' monitor.pk %}">{{monitor.serial_number|upper}}
                                </a>
                            </td>
                            <td>{{monitor.model.name|upper}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </section>
</div>

{% endblock content %}

app/templates/assets/monitormodel_detail.html
{% extends 'base.html' %}


{% block content %}
<div class="container py-5 mb-5">
    <h1>{{object}}</h1>
    <hr>
    <div class="row">
        <p>Maker: {{object.maker}}</p>
        <div class="text-end">
            <a class="text-dark"
                href="{% url 'monitor-model-update' object.pk %}">Edit</a>
        </div>
        <hr>
        <p>Monitors</p>
        <ol>
            {% for monitor in object.monitors.all %}
            <li><a href="{{monitor.get_absolute_url}}">{{monitor}}</a></li>
            {% endfor %}
        </ol>
    </div>
</div>
{% endblock content %}

app/templates/assets/monitormodel_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container py-5 mb-5">
    <h1>Add Monitor</h1>
    <hr>
    <form action=""
        enctype="multipart/form-data"
        method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="d-grid">
            <button class="btn btn-dark"
                type="submit">Submit</button>
        </div>
    </form>
</div>
{% endblock content %}

app/templates/assets/printer_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="p-5 mb-5">
    <h1>Add Printer</h1>
    <hr>
    <div class="col-lg-6 p-5 border-dark border rounded-4">
        <form action=""
            method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="d-grid">
                <button class="btn btn-dark rounded-4"
                    type="submit">Submit</button>
            </div>
        </form>
    </div>
</div>
<script>
    $("#id_model").select2();
    $("#id_department").select2();
    $("#id_location").select2();
</script>
{% endblock content %}