app/cf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("assets/", include("assets.urls")),
    path("customers", include("customers.urls")),
    path("", include("tickets.urls")),
    path("", include("pwa.urls")),
    # path("accounts/", include("allauth.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/tickets/urls.py
from django.urls import path

from .views import (
    CustomerTicketListView,
    TicketDetailView,
    TicketListView,
    TicketUpdateView,
    add_comment_view,
    assign_technician_view,
    create_ticket_view,
)

urlpatterns = [
    path("", create_ticket_view, name="ticket-create"),
    path("tickets/", CustomerTicketListView.as_view(), name="customer-ticket-list"),
    path("customer/ticket/", TicketListView.as_view(), name="ticket-list"),
    path(
        "tickets/detail/<slug:slug>/", TicketDetailView.as_view(), name="ticket-detail"
    ),
    path(
        "tickets/update/<slug:slug>/", TicketUpdateView.as_view(), name="ticket-update"
    ),
    path(
        "assign-technician/<slug:slug>/",
        assign_technician_view,
        name="assign-technician",
    ),
    path("ticket/add-comment/<slug:slug>/", add_comment_view, name="add-comment"),
]

app/assets/models.py
from customers.models import Customer, Department
from django.db import models
from django.shortcuts import reverse


# class ComputerName(models.Model):
#     computer_name = models.CharField(max_length=100, unique=True)
#     last_used_number = models.IntegerField(default=0)

#     def save(self, *args, **kwargs):
#         if not self.pk:  # Checking if the instance is not yet saved
#             computer_name_prefix = 'MCWT'
#             last_computer_name = ComputerName.objects.order_by("-last_used_number").first()
#             if last_computer_name:
#                 self.last_used_number = last_computer_name.last_used_number + 1
#             else:
#                 self.last_used_number = 1  # Start from 1 if no records exist
#             self.computer_name = f"{computer_name_prefix}{self.last_used_number}"
#         super().save(*args, **kwargs)

#     def __str__(self):
#         return self.computer_name


class Project(models.Model):
    name = models.CharField(max_length=100)
    details = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class Location(models.Model):
    name = models.CharField(max_length=100)
    details = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name.upper()


class Maker(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name.upper()


class Status(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "Statuses"
        ordering = ["name"]

    def __str__(self):
        return self.name.upper()


class OperatingSystem(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class MonitorModel(models.Model):
    name = models.CharField(max_length=100)
    maker = models.ForeignKey(Maker, on_delete=models.CASCADE)
    image = models.FileField(upload_to="monitor_models/", blank=True, null=True)

    class Meta:
        ordering = ["name"]

    def get_absolute_url(self):
        return reverse("monitor-model-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return f"{self.maker} - {self.name}"


class Monitor(models.Model):
    serial_number = models.CharField(max_length=100, blank=True, null=True)
    model = models.ForeignKey(
        MonitorModel, on_delete=models.CASCADE, related_name="monitors"
    )
    date_received = models.DateField(blank=True, null=True)
    date_installed = models.DateField(blank=True, null=True)
    notes = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ["model__name"]

    def get_absolute_url(self):
        return reverse("monitor-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return f"{self.model.name} - {self.serial_number}"


class ComputerType(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name.upper()


class ComputerModel(models.Model):
    name = models.CharField(max_length=100)
    computer_type = models.ForeignKey(ComputerType, on_delete=models.CASCADE)
    maker = models.ForeignKey(Maker, on_delete=models.CASCADE)
    processor = models.CharField(
        max_length=100, blank=True, null=True, help_text="In GHz(e.g.:i5 2.9 GHz)"
    )
    ram = models.IntegerField("RAM", help_text="In GB")
    hdd = models.IntegerField("HDD/Storage", help_text="In GB")

    class Meta:
        ordering = ["name"]

    def get_absolute_url(self):
        return reverse("computer-model-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return f"{self.maker} - {self.name} - {self.processor}"


class Computer(models.Model):
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE,
        related_name="projects",
        null=True,
        blank=True,
    )
    serial_number = models.CharField(max_length=100, blank=True, null=True)
    warranty_info = models.CharField("Warranty", max_length=100)
    computer_name = models.CharField(max_length=100, blank=True, null=True)
    model = models.ForeignKey(
        ComputerModel, on_delete=models.CASCADE, related_name="computers"
    )
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    monitor = models.ManyToManyField(Monitor, related_name="monitors", blank=True)
    os = models.ForeignKey(
        OperatingSystem,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="Operating System",
    )
    location = models.ForeignKey(
        Location,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name="computer_locations",
    )
    department = models.ForeignKey(
        Department,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name="computer_departments",
    )
    user = models.CharField(max_length=100, blank=True, null=True)
    date_received = models.DateField(blank=True, null=True)
    date_installed = models.DateField(blank=True, null=True)
    image = models.FileField(upload_to="system_audit/", blank=True, null=True)
    notes = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ["computer_name"]

    def get_absolute_url(self):
        return reverse("computer-detail", kwargs={"pk": self.pk})

    def __str__(self):
        if self.serial_number:
            return self.serial_number
        return self.computer_name


class ComputerComment(models.Model):
    computer = models.ForeignKey(
        Computer, on_delete=models.CASCADE, related_name="comments"
    )
    comment = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.computer.computer_name} - comment {self.pk}"


class PrinterModel(models.Model):
    name = models.CharField(max_length=100)
    maker = models.ForeignKey(Maker, on_delete=models.CASCADE)
    image = models.FileField(upload_to="printer_models/", blank=True, null=True)

    class Meta:
        ordering = ["name"]

    def get_absolute_url(self):
        return reverse("printer-model-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return f"{self.maker} - {self.name}"


class Printer(models.Model):
    serial_number = models.CharField(max_length=100, blank=True, null=True)
    printer_name = models.CharField(max_length=100, blank=True, null=True)
    model = models.ForeignKey(
        PrinterModel, on_delete=models.CASCADE, related_name="printers"
    )
    ip_addr = models.GenericIPAddressField("IP Address", blank=True, null=True)
    location = models.ForeignKey(
        Location,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name="printer_locations",
    )
    department = models.ForeignKey(
        Department,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name="printer_departments",
    )
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    date_received = models.DateField(blank=True, null=True)
    date_installed = models.DateField(blank=True, null=True)
    notes = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ["ip_addr"]

    def get_absolute_url(self):
        return reverse("printer-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return f"{self.model.maker} - {self.model.name}"


class MicrosoftOfficeVersion(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return f"Microsoft Office {self.name}"


class MicrosoftOffice(models.Model):
    version = models.ForeignKey(
        MicrosoftOfficeVersion, on_delete=models.CASCADE, related_name="versions"
    )
    product_key = models.CharField(max_length=30, unique=True)
    computer = models.ForeignKey(
        Computer,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        help_text="serial number",
        related_name="office_installations",
    )
    date_installed = models.DateField(blank=True, null=True)
    comments = models.TextField(blank=True, null=True)
    is_installed = models.BooleanField(default=False)
    has_failed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-date_installed"]

    def get_absolute_url(self):
        return reverse("microsoft-office-detail", kwargs={"pk": self.pk})

    def remove_hyphens(self):
        return self.product_key.replace("-", "")

    def __str__(self):
        return f"{self.version} - XXXXX-XXXXX-XXXXX-{self.product_key[-11:]}"

app/tickets/forms.py
from django import forms
from technicians.models import Technician

from .models import Comment, Ticket


class TicketUpdateForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = "__all__"
        widgets = {
            "status": forms.Select(attrs={"class": "form-control"}),
            "technician": forms.Select(attrs={"class": "form-control"}),
        }


class TicketAssignTechnicianForm(forms.Form):
    technician_id = forms.ModelChoiceField(
        queryset=Technician.objects.all(), empty_label="Select Technician"
    )


class TicketCreateForm(forms.Form):
    summary = forms.CharField(max_length=100)
    file = forms.FileField(required=False, widget=forms.ClearableFileInput())
    email = forms.EmailField(max_length=100)
    description = forms.CharField(widget=forms.Textarea)


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["comments"]

        widgets = {
            "comments": forms.Textarea(attrs={"rows": 3, "cols": 30}),
        }

app/tickets/views.py
from customers.models import Customer
from django.contrib import messages
from django.contrib.sites.models import Site
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import send_mail
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.html import strip_tags
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from technicians.models import Technician

from .forms import CommentCreateForm, TicketCreateForm, TicketUpdateForm, TicketAssignTechnicianForm
from .models import Comment, Ticket


class TicketUpdateView(UpdateView):
    model = Ticket
    form_class = TicketUpdateForm


def assign_technician_view(request, slug):
    ticket = get_object_or_404(Ticket, slug=slug)

    if request.method == "POST":
        form = TicketAssignTechnicianForm(request.POST)
        if form.is_valid():
            technician_id = form.cleaned_data["technician_id"]
            technician = get_object_or_404(Technician, id=technician_id.id)
            ticket.assigned_to = technician
            ticket.save()
            return redirect("ticket-detail", slug=ticket.slug)
    else:
        form = AssignTechnicianForm()

    return render(
        request, "tickets/assign_technician.html", {"form": form, "ticket": ticket}
    )


def create_ticket_view(request):
    if request.method == "POST":
        form = TicketCreateForm(request.POST, request.FILES)
        if form.is_valid():
            email = form.cleaned_data["email"]
            summary = form.cleaned_data["summary"]
            description = form.cleaned_data["description"]
            file = form.cleaned_data["file"]
            print(file, "file")

            try:
                customer = Customer.objects.get(email=email)
            except ObjectDoesNotExist:
                # Add a custom error to the form for the email field
                form.add_error(
                    "email", "Email address not found, please contact support"
                )
                return render(request, "tickets/create_ticket.html", {"form": form})

            ticket = Ticket.objects.create(
                user=customer, summary=summary, file=file, description=description
            )
            ticket.save()
            send_ticket_creation_email(ticket, email)
            messages.success(request, "Ticket was created successfully")
            return redirect("ticket-detail", slug=ticket.slug)
    else:
        form = TicketCreateForm()

    context = {"form": form}
    return render(request, "tickets/create_ticket.html", context)


def send_ticket_creation_email(ticket, recipient_email):
    current_site = Site.objects.get_current()
    domain = current_site.domain

    subject = f"New Ticket {ticket.ticket_id}"
    ticket_url = reverse("ticket-detail", kwargs={"slug": ticket.slug})
    full_url = f"http://{domain}{ticket_url}"

    html_message = render_to_string(
        "tickets/email_template.html", {"ticket": ticket, "full_url": full_url}
    )
    plain_message = strip_tags(html_message)

    send_mail(
        subject,
        plain_message,
        "swelanauguste@gmail.com",
        [recipient_email],
        html_message=html_message,
    )


class TicketListView(ListView):
    model = Ticket
    paginate_by = 25


class CustomerTicketListView(ListView):
    model = Ticket
    template_name = "tickets/customer_ticket_list.html"

    def get_queryset(self):
        query = self.request.GET.get("ticket")

        if query:
            return Ticket.objects.filter(Q(ticket_id__iexact=query)).distinct()
        return Ticket.objects.none()


class TicketDetailView(DetailView):
    model = Ticket

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["comment_form"] = CommentCreateForm()
        context["assign_technician_form"] = TicketAssignTechnicianForm()
        return context


def add_comment_view(request, slug):
    ticket = get_object_or_404(Ticket, slug=slug)

    if request.method == "POST":
        form = CommentCreateForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.ticket = ticket
            comment.save()
            return redirect("ticket-detail", slug=slug)

    # If the form is not valid or the request method is not POST
    return render(
        request, "ticket_detail.html", {"ticket": ticket, "comment_form": form}
    )

app/templates/tickets/assign_technician.html
<h2>Assign Technician to Ticket</h2>

<form method="post"
    action="{% url 'assign-technician' ticket.slug %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Assign Technician</button>
</form>

app/templates/tickets/create_ticket.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="p-5 mb-5">
    <div class="col-lg-4 p-5 rounded-4 border shadow">
        <h1>Create ticket</h1>
        <hr>
        <br>
        <form action=""
            enctype="multipart/form-data"
            method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="d-grid">
                <button class="btn btn-dark"
                    type="submit">Submit</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

app/templates/tickets/email_template.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, initial-scale=1.0">
    <title>New Ticket Created</title>
</head>

<body>
    <h2>New Ticket: {{ ticket.ticket_id|upper }} Created</h2>
    <p>Dear {{ ticket.user }},</p>
    <p>A new ticket has been created. Here are the details:</p>

    <p><strong>Ticket ID:</strong> {{ ticket.ticket_id }}</p>
    <p><strong>Description:</strong> {{ ticket.description }}</p>

    <p>You can view the details of the ticket by clicking on the following
        link:</p>

    <p><a href="{{full_url}}">View Ticket</a></p>

    <p>Thank you for using our ticketing system.</p>

    <p>Best regards,
        <br>Your Support Team
    </p>
</body>

</html>

app/templates/tickets/ticket_detail.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% load humanize %}


{% block content %}
<div class="container py-5 mb-5">
    <h1>{{object.summary}} ({{object}})
        {% if object.file %}
        <a target="_blank"
            href="{{object.file.url}}">
            <span class="material-symbols-outlined fs-1 text-danger">
                attach_file
            </span></a>
        {% endif %}
    </h1>
    <hr>
    <div class="row">
        <div class="bg-light px-5 py-3 rounded-4 shadow">

            <p>{{object.description}}</p>
            <div class="text-end">
                <span
                    class="small text-muted">{{object.created_at|naturaltime}}</span>
            </div>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col">
            {% if not object.assigned_to %}

            <h2>Assign Technician to Ticket</h2>

            <form method="post"
                action="{% url 'assign-technician' ticket.slug %}">
                {% csrf_token %}
                {{ assign_technician_form|crispy }}
                <div class="d-grid">
                    <button class="btn btn-dark"
                        type="submit">Assign Technician</button>
                </div>
            </form>
            <br>
            {% else %}
            <p>Assigned To: <span
                    class="fs-3 fw-bold">{{object.assigned_to}}</span>
            </p>

            {% endif %}
        </div>


        <div class="col-lg">
            <form method="post"
                action="{% url 'add-comment' object.slug %}">
                {% csrf_token %}
                {{ comment_form|crispy }}
                <div class="d-grid">
                    <button class="btn btn-dark"
                        type="submit">Add Comment</button>
                </div>
            </form>
        </div>
    </div>
    <br>
    <section>
        <div class="row">
            <div class="col">
                <h3>Comments</h3>
                {% for comment in object.comments.all %}
                <p class="border p-3 rounded-4 shadow bg-info bg-opacity-10">
                    {{ comment.comments }}
                    <span
                        class="ms-3 small text-muted">{{comment.created_at|naturaltime}}</span>
                </p>
                {% endfor %}
            </div>

        </div>
    </section>
</div>
{% endblock content %}

app/templates/tickets/ticket_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="p-5 mb-5">
    <h1>Add Computer</h1>
    <hr>
    <div class="row">
        <div class="col-lg-6 p-5 border border-dark rounded-4">
            <form action=""
                enctype="multipart/form-data"
                method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="d-grid">
                    <button class="btn btn-dark"
                        type="submit">Submit</button>
                </div>
            </form>
        </div>
        <!-- <div class="col p-5">

            <h3>Next new computer name</h3>
            <form action="{% url 'get-next-computer-name' %}"
                method="post">
                <p>{{last_computer_name}}</p>
                {{get_computer_name_form|crispy}}
                <button class="btn btn-dark px-5 rounded-4"
                    type="submit">Use name</button>
            </form>
        </div> -->
    </div>
</div>
<script>
    $("#id_model").select2();
    $("#id_os").select2();
    $("#id_department").select2();
    $("#id_monitor").select2();
</script>
{% endblock content %}

app/templates/tickets/ticket_list.html
{% extends 'base.html' %}

{% load humanize %}

{% block content %}
<div class="p-5 mb-5">
    <h1>Tickets</h1>
    <div class="text-end">
        <a href="{% url 'ticket-create' %}">
            <span class="text-success material-symbols-outlined">
                add_box
            </span>
        </a>
    </div>
    <div class="col-lg-6 mx-auto py-3">
        <form action=""
            method="get">
            <input class="form-control form-control-lg rounded-pill"
                type="search"
                name="ticket"
                placeholder="Ticket ID"
                id="">
        </form>
    </div>
    <br>
    <div class="table responsive">
        <table class="table table-sm table-hover small">
            <tbody>
                {% for ticket in object_list %}
                <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td><a class="text-dark"
                            href="{{ticket.get_absolute_url}}">{{ticket.summary}}</a>
                    </td>
                    <td>{{ticket.ticket_id}} - <span class="small text-muted">
                            {{ticket.created_at|naturaltime}}</span></td>
                    <td>{{ticket.user}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

</div>
{% endblock content %}